// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ForeignCluster defines model for ForeignCluster.
type ForeignCluster struct {
	Id              string `json:"id"`
	IncomingPeering bool   `json:"incoming_peering"`
	Ip              string `json:"ip"`
	Name            string `json:"name"`
	OutgoingPeering bool   `json:"outgoing_peering"`
	RawYaml         string `json:"raw_yaml"`
}

// ResourceOffer defines model for ResourceOffer.
type ResourceOffer struct {
	Cluster   string                 `json:"cluster"`
	Id        string                 `json:"id"`
	Resources map[string]interface{} `json:"resources"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns a list of all foreign clusters
	// (GET /clusters)
	GetClusters(ctx echo.Context) error
	// Returns a list of all resource offers we present to other clusters
	// (GET /resources/remote)
	GetResourcesRemote(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClusters converts echo context to params.
func (w *ServerInterfaceWrapper) GetClusters(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetClusters(ctx)
	return err
}

// GetResourcesRemote converts echo context to params.
func (w *ServerInterfaceWrapper) GetResourcesRemote(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetResourcesRemote(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/clusters", wrapper.GetClusters)
	router.GET(baseURL+"/resources/remote", wrapper.GetResourcesRemote)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7yUUW/aMBDHv4p128MmhSSEwCBvVbVVnbq1on2bpsqES3AV+1zbaYcqvvtkQ2iBaJr2",
	"sL402Pe/+9/vbL9ASVKTQuUsFC9gyxVKHj6/kEFRq/OmtQ6NX8FfXOoG/adYQgHjdDmb5pPxIF1wHOR5",
	"Vg6mOMXBcJLmk2U+nmTlGCIQqiQpVH2vEY1QNRQVbyxGIDQUMPyUxVkap/EQIlBcIhRwQ424u2ZXfGEh",
	"AmpdTQd6Z1rcRKANaTROoO0svYBba5/BuhC56au+D1oQNchViNK94q2fno1TT31ZDX++X3PZ9KTwu/jY",
	"CoNLKH5487tqwUuP7Z6abwr8jLoCtHjA0vnqc7TUmhKvq+pkfma3F8iVuoUCstF4KiEC1CuUaHgzsI4M",
	"r33S0Xg2HOWzfJxNIYJVW6PmNdrB8EJAAenBWvatW5Moyax96mmep+HPd/kkloLHJcmk9oWzCDQtLRQw",
	"mwUuh2MtX8/f6Wz7R37Q3BGWPu5dibfKU6CbcJgq8kmXaEsjtBOkoIAzNv98e8fObi5ZRYZdiUdiH1bO",
	"aVskSSMeKRb0MYYInHAeP4SITgMRPKGx21TDOI3TcMA0Kq49ydHubmjuVqGjZOc3/KjR+X+eGPd2Lv3F",
	"vEB33sWEpjQpu8WRpWmgSsqhClKudSPKIE4erHfRPQPhVjmUQfjeYAUFvEteH4xk91okR0/FZs+OG8PX",
	"W3THyL7eXn9nYZ9RxXYtMQ/YyGAmzMq2UvJwhuboWqMs46wR1nkNbxrP21dmeyRelOzHmBiU5PBPoLpb",
	"Yufb0P/B6/Bm/gOurkFGPoP9K1RHGvaMTBu0qBxzxMit0LzFuNn8DgAA//9fttcSHAYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
